name: optimizationII
channels:
  - conda-forge
dependencies:
  - ipython
  - ipywidgets
  - jupyter
  - jupyterlab
  - matplotlib
  - numpy
  - pandas
  - pandoc
  - pip
  - python=3.8
  - scipy
  - seaborn
  - sphinx
  - tqdm
  - pip:
    - black
    - cvxpy
    - jupyterlab_code_formatter
    - nbsphinx
    - nbsphinx_link
    - pycodestyle
    - pygments==2.7.1
    - sphinx-autobuild
    - sphinx-copybutton
    - sphinx_rtd_theme==0.5.0